version: "3"
services:
    #PHP Service
    yes-php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        image: fff.agency/php-laravel
        container_name: yes-php
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: yes-php
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - yes-network

    #Nginx Service
    yes-web:
        image: nginx:alpine
        container_name: yes-web
        restart: unless-stopped
        tty: true
        ports:
            - "8070:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - .docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - yes-network

    #MySQL Service
    yes-mysql:
        image: mariadb:10.5.8
        container_name: yes-mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: f0rmfunfunc1on!
            SERVICE_TAGS: dev
            SERVICE_NAME: yes-mysql
        volumes:
            - mysqldata:/var/lib/mysql
            - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - yes-network

    yes-redis:
        image: "redis:alpine"
        container_name: yes-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - "redisdata:/data"
        networks:
            - yes-network

    yes-mailhog:
        image: "mailhog/mailhog:latest"
        container_name: yes-mailhog
        restart: unless-stopped
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - yes-network

#Docker Networks
networks:
    yes-network:
        driver: bridge

#Volumes
volumes:
    mysqldata:
        driver: local
    redisdata:
        driver: local
